### ISSUE TITLE
Pushen der Datenbankdateien

### ISSUE THREAD

**Issue by darkloyd15** [darkloyd15/Warenbestand_Fahrradladen#10]
@mohamadlatah Bitte lade wie besprochen die Datenbankdateien hoch
![ER_Diagram](https://user-images.githubusercontent.com/91872432/150641442-2261b820-60a8-4f41-ac6b-e697ff1aad22.png)
.

**Comment by mohamadlatah** [comment]
[Create_DB_Warenbestand_FL.txt](https://github.com/darkloyd15/Warenbestand_Fahrradladen/files/7924342/Create_DB_Warenbestand_FL.txt)

**Comment by mohamadlatah** [comment]
Code zum Anlegen der Datenbank erledigt
