### ISSUE TITLE
Erweiterung des Grafikprogramms

### ISSUE THREAD

**Issue by darkloyd15** [darkloyd15/Warenbestand_Fahrradladen#9]
Bitte füge folgende Ansichten zu unserem Programm hinzu @dcrnv
[Layout_Warenbestand.docx](https://github.com/darkloyd15/Warenbestand_Fahrradladen/files/7918469/Layout_Warenbestand.docx)

**Comment by dcrnv** [comment]
Wurde hinzugefügt
